@startuml
left to right direction

class UserServiceImpl {
    -userRepository: UserRepository
    -authorityRepository: AuthorityRepository
    -userMapper: UserMapper
    -userCreateMapper: UserCreateMapper
    -userListMapper: UserListMapper

    +UserServiceImpl(userRepository: UserRepository, authorityRepository: AuthorityRepository,
                     userCreateMapper: UserCreateMapper, userMapper: UserMapper, userListMapper: UserListMapper)
    +createUser(userCreateDTO: UserCreateDTO): UserDTO
    +getById(id: Long): UserDTO
    +getAll(pageable: Pageable): Page<UserDTO>
    +updateById(id: Long, userUpdateDTO: UserUpdateDTO): UserDTO
    +deleteById(id: Long): void
    +addAuthoritiesToUser(id: Long, authorities: Set<Authority>): UserDTO
    +removeAuthorityFromUser(id: Long, authority: Authority): UserDTO
    +getUserByRole(userRole: UserRole, pageable: Pageable): Page<UserListDTO>
    +existsByUsernameOrEmail(username: String, email: String): boolean
    +changePassword(id: Long, newPassword: String): void
}

UserServiceImpl --> UserRepository
UserServiceImpl --> AuthorityRepository
UserServiceImpl --> UserCreateMapper
UserServiceImpl --> UserMapper
UserServiceImpl --> UserListMapper
@enduml